### ISSUE TITLE
`db2view nmap` lead to Mongodb, Sort exceeded memory limit

### ISSUE THREAD

**Issue by YoranSys** [ivre/ivre#1311]
### IVRE Version

```bash
$ ivre version
root@88202b4fdf53:/#  ivre version
IVRE - Network recon framework
Copyright 2011 - 2020 Pierre LALET <pierre@droids-corp.org>
Version 0.9.17.dev142

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

Linux 88202b4fdf53 5.15.25-1-MANJARO #1 SMP PREEMPT Wed Feb 23 14:44:03 UTC 2022 x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.3.2
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.1.2
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 20.0.1
    Python module tinydb: missing

```

### Summary

Got an exception: `Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.` when `ivre db2view nmap`.

### Actual behavior

```python
root@88202b4fdf53:/# ivre db2view nmap
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 103, in <module>
    main()
  File "/usr/local/bin/ivre", line 71, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.9/dist-packages/ivre/tools/db2view.py", line 126, in main
    for elt in itr:
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 862, in to_view
    next_recs.append(next(itrs[i]))
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 805, in from_nmap
    for rec in db.nmap.get(flt, sort=[("addr", 1)]):
  File "/usr/local/lib/python3.9/dist-packages/ivre/db/mongo.py", line 1927, in get
    for host in self._get(spec, **kargs):
  File "/usr/lib/python3/dist-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python3/dist-packages/pymongo/cursor.py", line 1124, in _refresh
    self.__send_message(q)
  File "/usr/lib/python3/dist-packages/pymongo/cursor.py", line 999, in __send_message
    response = client._run_operation_with_response(
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1368, in _run_operation_with_response
    return self._retryable_read(
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1471, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1360, in _cmd
    return server.run_operation_with_response(
  File "/usr/lib/python3/dist-packages/pymongo/server.py", line 136, in run_operation_with_response
    _check_command_response(
  File "/usr/lib/python3/dist-packages/pymongo/helpers.py", line 167, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response,
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting., full error: {'ok': 0.0, 'errmsg': 'Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.', 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed'}
```

**Comment by p-l-** [comment]
That's interesting, thanks for reporting this bug. Did you create the indexes in the scan & view collections? That could be the root cause and, be the cause of (very) poor performances.

Can you repoort the output of the following commands in a python shell?
```Python
>>> from ivre.db import db
>>> len(db.nmap.db[db.nmap.columns[db.nmap.column_hosts]].index_information())
XXX report this value XXX
>>> len(db.view.db[db.view.columns[db.view.column_hosts]].index_information())
XXX report this value XXX
```

**Comment by YoranSys** [comment]
Hi @p-l-,
You are right, it seems that some indexes were missing.

It's ok now. 

Thanks for your help.

**Comment by Altegro** [comment]
Hi I have the same problem after a clean install. Maybe you should use `allowDiskUse` in aggregations ?

`
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 103, in <module>
    main()
  File "/usr/local/bin/ivre", line 71, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.9/dist-packages/ivre/tools/db2view.py", line 126, in main
    for elt in itr:
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 864, in to_view
    next_recs.append(next(itrs[i]))
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 807, in from_nmap
    for rec in db.nmap.get(flt, sort=[("addr", 1)]):
  File "/usr/local/lib/python3.9/dist-packages/ivre/db/mongo.py", line 1968, in get
    for host in self._get(spec, **kargs):
  File "/usr/local/lib/python3.9/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.9/dist-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/mongo_client.py", line 1267, in _run_operation
    return self._retryable_read(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/mongo_client.py", line 1371, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/mongo_client.py", line 1263, in _cmd
    return server.run_operation(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/server.py", line 134, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/helpers.py", line 180, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting., full error: {'ok': 0.0, 'errmsg': 'Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.', 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed'}
`
-------------------------
>>> len(db.view.db[db.view.columns[db.view.column_hosts]].index_information())
1
>>> len(db.nmap.db[db.nmap.columns[db.nmap.column_hosts]].index_information())
1
------------------------

**Comment by p-l-** [comment]
Hi @Altegro

> Hi I have the same problem after a clean install. Maybe you should use `allowDiskUse` in aggregations ?

Certainly not. If you see this error, that's because you do not have the indexes. This would cause poor performances. In the installation instructions, the indexes are created using `--init` for all the CLI tools. Given the output of the `len()` calls you provide, you may have skipped that part.

**Comment by Altegro** [comment]
I looked at the instruction badly and trusted docker-compose. My mistake.
Everything is working now after I used the following commands in the 'ivreclient' container

```bash
$ yes | ivre ipinfo --init
$ yes | ivre scancli --init
$ yes | ivre view --init
$ yes | ivre flowcli --init
$ yes | sudo ivre runscansagentdb --init
```

```python3
>>> from ivre.db import db
>>> len(db.nmap.db[db.nmap.columns[db.nmap.column_hosts]].index_information())
54
>>> len(db.view.db[db.view.columns[db.view.column_hosts]].index_information())
54
```
