### ISSUE TITLE
Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting

### ISSUE THREAD

**Issue by Altegro** [ivre/ivre#1325]
Hi I have the same problem after a clean install. Maybe you should use `allowDiskUse` in aggregations ?
Error appears when trying `db2view nmap` on >100Mb folder

```python3
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 103, in <module>
    main()
  File "/usr/local/bin/ivre", line 71, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.9/dist-packages/ivre/tools/db2view.py", line 126, in main
    for elt in itr:
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 864, in to_view
    next_recs.append(next(itrs[i]))
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 807, in from_nmap
    for rec in db.nmap.get(flt, sort=[("addr", 1)]):
  File "/usr/local/lib/python3.9/dist-packages/ivre/db/mongo.py", line 1968, in get
    for host in self._get(spec, **kargs):
  File "/usr/local/lib/python3.9/dist-packages/pymongo/cursor.py", line 1248, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.9/dist-packages/pymongo/cursor.py", line 1165, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/cursor.py", line 1052, in __send_message
    response = client._run_operation(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/mongo_client.py", line 1267, in _run_operation
    return self._retryable_read(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/mongo_client.py", line 1371, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/mongo_client.py", line 1263, in _cmd
    return server.run_operation(
  File "/usr/local/lib/python3.9/dist-packages/pymongo/server.py", line 134, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/usr/local/lib/python3.9/dist-packages/pymongo/helpers.py", line 180, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting., full error: {'ok': 0.0, 'errmsg': 'Executor error during find command :: caused by :: Sort exceeded memory limit of 104857600 bytes, but did not opt in to external sorting.', 'code': 292, 'codeName': 'QueryExceededMemoryLimitNoDiskUseAllowed'}
```

```python3
>>> len(db.view.db[db.view.columns[db.view.column_hosts]].index_information())
1
>>> len(db.nmap.db[db.nmap.columns[db.nmap.column_hosts]].index_information())
1
```

**Comment by p-l-** [comment]
Hi, see my comment in #1311. You must create the indexes.

**Comment by Altegro** [comment]
I looked at the instruction badly and trusted docker-compose. My mistake.
Everything is working now after I used the following commands in the 'ivreclient' container

```bash
$ yes | ivre ipinfo --init
$ yes | ivre scancli --init
$ yes | ivre view --init
$ yes | ivre flowcli --init
$ yes | sudo ivre runscansagentdb --init
```

```python3
>>> from ivre.db import db
>>> len(db.nmap.db[db.nmap.columns[db.nmap.column_hosts]].index_information())
54
>>> len(db.view.db[db.view.columns[db.view.column_hosts]].index_information())
54
```
