### ISSUE TITLE
Problems to open ivre

### ISSUE THREAD

**Issue by AkumuKernel** [ivre/ivre#1432]
Hi Hi I have this problem
```
$ ivre
Traceback (most recent call last):
  File "/sbin/ivre", line 39, in <module>
    from ivre import utils, tools  # noqa: E402
  File "/usr/lib/python3.10/site-packages/ivre/utils.py", line 73, in <module>
    from OpenSSL import crypto as osslc  # type: ignore
  File "/usr/lib/python3.10/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3.10/site-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3.10/site-packages/OpenSSL/crypto.py", line 3224, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

```

**Comment by p-l-** [comment]
Hi there! How did you install IVRE? What is your OS / version?
I think this problem is not related to IVRE but rather to your install of the `pyOpenSSL` package.

**Comment by AkumuKernel** [comment]
I install IVRE via BlackArch Linux repositories, my version from BlackArch is 5.19.12-arch1-1

**Comment by p-l-** [comment]
Can you run the following command and report the result?
```bash
python -c "import OpenSSL; print(OpenSSL.__version__)"
```

**Comment by p-l-** [comment]
Closed for inactivity. Please reopen if needed.
