### ISSUE TITLE
db2view error: CursorNotFound (code 43)

### ISSUE THREAD

**Issue by 0xDeva** [ivre/ivre#1436]
Got an exception while running db2view (after ~20h). It seems that this is due to a timer timeout in the mongo server. I don't think the exception was caught, so it stopped the indexation (?).

Ivre was installed using Vagrant.
I changed the timeout (using: `db.runCommand({setParameter:1, cursorTimeoutMillis: 1800000})` on mongosh) and tried again.

```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 103, in <module>
    main()
  File "/usr/local/bin/ivre", line 71, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.9/dist-packages/ivre/tools/db2view.py", line 125, in main
    for elt in itr:
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 929, in to_view
    next_recs[i] = next(itrs[i])
  File "/usr/local/lib/python3.9/dist-packages/ivre/view.py", line 851, in from_nmap
    for rec in db.nmap.get(flt, sort=[("addr", 1)]):
  File "/usr/local/lib/python3.9/dist-packages/ivre/db/mongo.py", line 1987, in get
    for host in self._get(spec, **kargs):
  File "/usr/lib/python3/dist-packages/pymongo/cursor.py", line 1207, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/python3/dist-packages/pymongo/cursor.py", line 1144, in _refresh
    self.__send_message(g)
  File "/usr/lib/python3/dist-packages/pymongo/cursor.py", line 999, in __send_message
    response = client._run_operation_with_response(
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1368, in _run_operation_with_response
    return self._retryable_read(
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1471, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1360, in _cmd
    return server.run_operation_with_response(
  File "/usr/lib/python3/dist-packages/pymongo/server.py", line 136, in run_operation_with_response
    _check_command_response(
  File "/usr/lib/python3/dist-packages/pymongo/helpers.py", line 163, in _check_command_response
    raise CursorNotFound(errmsg, code, response,
pymongo.errors.CursorNotFound: cursor id 7876382238126689573 not found, full error: {'ok': 0.0, 'errmsg': 'cursor id 7876382238126689573 not found', 'code': 43, 'codeName': 'CursorNotFound'}
```

**Comment by p-l-** [comment]
To be honest that's an issue I have often seen and never tackled... :see_no_evil:
But let's use the opportunity to improve IVRE!

Quick question first: did the insertion work after you changed the timeout value?

As a workaround, since the view creation is done per IP address, you can run separated `db2view` per network.
For example, if you are scanning the whole IPv4 space:
```bash
for i in {0..223}; do ivre db2view --no-merge nmap --net $i.0.0.0/8; done
```
With some `xargs` magic you can even parallelize that.

**Comment by p-l-** [comment]
Hey @0xDeva could you try if the patch proposed in #1440 fixes the problem in your environment?

**Comment by 0xDeva** [comment]
Hey @p-l- , awesome, thanks for the quick patch! Will try it tomorrow and keep you updated.
For info, changing the timeout didn't work, I got the same issue after few minutes.

**Comment by 0xDeva** [comment]
db2view has been running without any issue for the last 24 hours, thanks!

**Comment by p-l-** [comment]
Yes! That's a very old bug and I'm super happy we've been able to kill it. Thanks a lot for your report and help @0xDeva!
