### ISSUE TITLE
int2ip function does not work for int saved IPs

### ISSUE THREAD

**Issue by timh2os** [ivre/ivre#1492]
### IVRE Version

```
IVRE - Network recon framework
Copyright 2011 - 2022 Pierre LALET <pierre@droids-corp.org>
Version 0.9.18.dev124-dockerhub

Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110]

Linux 32b9d98d0f39 5.4.0-136-generic #153-Ubuntu SMP Thu Nov 24 15:56:58 UTC 2022 x86_64

Dependencies:
    Python module pymongo: 3.11.0
    Python module sqlalchemy: missing
    Python module psycopg2: missing
    Python module cryptography: 3.3.2
    Python module krbV: missing
    Python module pycurl: missing
    Python module PIL: 8.1.2
    Python module MySQLdb: missing
    Python module dbus: missing
    Python module matplotlib: missing
    Python module bottle: 0.12.19
    Python module OpenSSL: 20.0.1
    Python module tinydb: missing

```

### Summary

While trying to convert an IP address from integer notation to dotted IP notation using int2ip, the function errors out  stating the integer is too large to convert.

### Expected behavior

Using the int2ip function, IP's from the database can be converted back to IP dotted notation. 
 
### Actual behavior

I ran in to this by doing:
```
flt = db.nmap.searchcert(sha1="<CERT>"))
x = db.view.diff_categories('INTERNAL','EXTERNAL', flt)
cur = inter(x)
for y in cur:
   print(ivre.utils.int2ip(y['addr'][0]))
```
Debugging this further, I noticed that values (e.g -549755813888) can in fact be translated by other tools (CyberChef -> 0.0.0.0).
This indicates the value itself is correct.

error message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ivre/utils.py", line 255, in int2ip
    return socket.inet_ntoa(struct.pack("!I", ipint))
struct.error: argument out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ivre-share/modules/diff.py", line 16, in DiffPortExternalInternal
    print(ivre.utils.int2ip(y['addr'][0]))
  File "/usr/local/lib/python3.9/dist-packages/ivre/utils.py", line 259, in int2ip
    struct.pack("!QQ", ipint >> 64, ipint & 0xFFFFFFFFFFFFFFFF),
struct.error: int too large to convert
```

### How to reproduce

See code above

**Comment by p-l-** [comment]
CyberChef is wrong here (0.0.0.0 would probably be... 0?)

The version of IVRE you are using is old and this bug has been reported (in a comment in #1463) 1 year and 3 months ago and fixed (in #1467) the following day.

Please update IVRE before reporting bugs, it will save time for everyone!

**Comment by timh2os** [comment]
Hi,

Yes. I would have loved to save that time as well. I did look for this, and found the earlier report. I obviously did not read all the comments, as that issue involved IPv6 and looked more of a feature request than a bug.

You are right on updating IVRE though. I'll make sure to remember next time.

________________________________
Van: Pierre ***@***.***>
Verzonden: maandag, maart 6, 2023 10:17 AM
Aan: ivre/ivre ***@***.***>
CC: Tim Waters ***@***.***>; Author ***@***.***>
Onderwerp: Re: [ivre/ivre] int2ip function does not work for int saved IPs (Issue #1492)


CyberChef is wrong here (0.0.0.0 would probably be... 0?)

The version of IVRE you are using is old and this bug has been reported (in a comment in #1463<https://github.com/ivre/ivre/discussions/1463>) 1 year and 3 months ago and fixed (in #1467<https://github.com/ivre/ivre/pull/1467>) the following day.

Please update IVRE before reporting bugs, it will save time for everyone!

**Comment by p-l-** [comment]
I don't think the PR or the comment mention IPv6. It was only about the `addr` field and concerned both IPv4 and IPv6.
