### ISSUE TITLE
[Ivre DB] CPU high usage

### ISSUE THREAD

**Issue by Amerousful** [ivre/ivre#1525]
### IVRE Version
```
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev81-dockerhub

Python 3.9.2 (default, Feb 28 2021, 17:03:44)
[GCC 10.2.1 20210110]

Linux 4637a07134ad 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 x86_64

Dependencies:
    MySQLdb: *missing*
    OpenSSL: 20.0.1
    PIL: 8.1.2
    bottle: 0.12.19
    cryptography: 3.3.2
    dbus: *missing*
    krbV: *missing*
    matplotlib: *missing*
    psycopg2: *missing*
    pycurl: *missing*
    pymongo: 3.11.0
    sqlalchemy: *missing*
    tinydb: *missing*
```

### Summary

Hey! 
I installed Ivre with this [docker-compose ](https://github.com/ivre/ivre/blob/master/docker/docker-compose.yml), but something wrong with DB. CPU usage 100% and I can't run any command because it's connection timeout

### How to reproduce

1) clone https://github.com/ivre/ivre
2) cd docker
3) docker compose up
4) docker attach ivreclient
5) ivre ipinfo --init

### More

Output:
```
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.9/dist-packages/ivre/tools/ipinfo.py", line 318, in main
    dbase.init()
  File "/usr/local/lib/python3.9/dist-packages/ivre/db/mongo.py", line 298, in init
    self.db[colname].drop()
  File "/usr/lib/python3/dist-packages/pymongo/collection.py", line 1127, in drop
    dbo.drop_collection(self.__name, session=session)
  File "/usr/lib/python3/dist-packages/pymongo/database.py", line 921, in drop_collection
    with self.__client._socket_for_writes(session) as sock_info:
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1293, in _socket_for_writes
    server = self._select_server(writable_server_selector, session)
  File "/usr/lib/python3/dist-packages/pymongo/mongo_client.py", line 1278, in _select_server
    server = topology.select_server(server_selector)
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 241, in select_server
    return random.choice(self.select_servers(selector,
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 199, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/usr/lib/python3/dist-packages/pymongo/topology.py", line 215, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: ivredb:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 647dc0211cd52d962f330202, topology_type: Single, servers: [<ServerDescription ('ivredb', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('ivredb:27017: [Errno 111] Connection refused')>]>
```

docker stats:
```
CONTAINER ID   NAME         CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
7665faf6be0c   ivredoku     0.02%     26.91MiB / 11.68GiB   0.22%     1.34kB / 0B       0B / 4.1kB       8
a7dfb8f12563   ivredb       100.49%   16.38MiB / 11.68GiB   0.14%     10.4kB / 6.8kB    0B / 0B          4
4637a07134ad   ivreclient   0.00%     18.11MiB / 11.68GiB   0.15%     7.92kB / 9.24kB   10.7MB / 4.1kB   2
07ea27b2b99a   ivreuwsgi    0.02%     48.14MiB / 11.68GiB   0.40%     1.12kB / 0B       0B / 0B          4
7db0a8d39a27   ivreweb      0.00%     23.75MiB / 11.68GiB   0.20%     1.12kB / 0B       0B / 4.1kB       14
```

<img width="1432" alt="image 1984" src="https://github.com/ivre/ivre/assets/22199881/4a20c9eb-5748-4e88-895d-6cfcee0fd7f5">
<img width="1096" alt="image 1985" src="https://github.com/ivre/ivre/assets/22199881/95e87efd-ce54-4f02-a5ee-94b119afa637">

```uname -a
Darwin bairovp.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
```

**Comment by p-l-** [comment]
Thanks for this report. What do you have in the MongoDB logs (directory `var_log_mongodb`)? Looks like the MongoDB instance won't start for some reason.

**Comment by Amerousful** [comment]
@p-l- This problem relates to the Mac M1. I tried the same steps with Intel and everything was OK

Hm, I checked `/var/log/mongodb` and it's empty...

**Comment by p-l-** [comment]
Oh OK... then a solution should be to use the container provided by MongoDB rather than `ivre/db`. That's something I have in mind for the project anyway, so if you manage to do so, a PR would be more than welcome!

**Comment by Amerousful** [comment]
@p-l- just change image on 'mongo' ?

**Comment by p-l-** [comment]
I suppose it should work. Never tried, though.

**Comment by Amerousful** [comment]
https://github.com/ivre/ivre/pull/1529
Everything works. CPU about several percent. 

Thanks for your help!
