### ISSUE TITLE
Start docker ivre install ivre ipdata 404

### ISSUE THREAD

**Issue by gitingua** [ivre/ivre#1590]
$ ivre version
IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev135-dockerhub

Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

Linux 0c0e8abaa713 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64

Dependencies:
    MySQLdb: *missing*
    OpenSSL: 23.2.0
    PIL: 9.4.0
    bottle: 0.12.25
    cryptography: 41.0.4
    dbus: *missing*
    krbV: *missing*
    matplotlib: *missing*
    psycopg2: *missing*
    pycurl: *missing*
    pymongo: 4.5.0
    sqlalchemy: *missing*
    tinydb: *missing*
    elasticsearch: *missing*
    elasticsearch_dsl: *missing*

Python 3.8.2 (default, Feb 26 2020, 22:21:03)
[GCC 9.2.1 20200130]

Linux 5.10.0-25-amd64 #1 SMP Debian 5.10.191-1 (2023-08-16) x86_64 GNU/Linux

running command 
ivre ipdata --download

Downloading https://ivre.rocks/data/geolite/GeoLite2-City.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-City.tar.gz: Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ssl.py", line 1075, in _create
    self.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/ipdata.py", line 65, in main
    geoiputils.download_all(verbose=not args.quiet)
  File "/usr/local/lib/python3.11/dist-packages/ivre/geoiputils.py", line 227, in download_all
    with opener.open(url) as udesc, open(outfile, "wb") as wdesc:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)>

and also the page displays
https://ivre.rocks/data/geolite/GeoLite2-City.tar.gz 

404 Not Found
nginx

**Comment by ruevaughn** [comment]
You need to apt-get install ca-certificates or sudo apt-get install ca-certificates

**Comment by gitingua** [comment]
root@debian:/opt/test# sudo apt-get install ca-certificates
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20210119).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@debian:/opt/test#  docker start -I ivreclient



root@9a808ed967:/# ivre ipdata --download
Downloading https://ivre.rocks/data/geolite/GeoLite2-City.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-City.tar.gz: Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 941, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/ipdata.py", line 65, in main
    geoiputils.download_all(verbose=not args.quiet)
  File "/usr/local/lib/python3.11/dist-packages/ivre/geoiputils.py", line 227, in download_all
    with opener.open(url) as udesc, open(outfile, "wb") as wdesc:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
root@9a808ed967:/#

**Comment by p-l-** [comment]
Hi,
Thanks @gitingua for your report, and thank @ruevaughn for your answer.
This issue will be fixed in #1593, and the DNS error is most likely related to your network / Docker configuration, not to IVRE itself. Can you download something from your container at all (e.g., using curl)? Can you (e.g., with Python) connect to a remote server?

**Comment by p-l-** [comment]
The new images are being built and will soon be uploaded to the hub. Thanks again!
