### ISSUE TITLE
Missing Geo Data

### ISSUE THREAD

**Issue by hacks2learn** [ivre/ivre#1608]
### IVRE Version

```
root@1d8dba340b32:/# ivre version
IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev164-dockerhub

Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]

Linux 1d8dba340b32 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64

Dependencies:
    MySQLdb: *missing*
    OpenSSL: 23.3.0
    PIL: 9.4.0
    bottle: 0.12.25
    cryptography: 41.0.7
    dbus: *missing*
    krbV: *missing*
    matplotlib: *missing*
    psycopg2: *missing*
    pycurl: *missing*
    pymongo: 4.6.1
    sqlalchemy: *missing*
    tinydb: *missing*
    elasticsearch: *missing*
    elasticsearch_dsl: *missing*
```

### Summary

Installed via Vagrant / Docker and all seemed fine.  Then while trying to perform the initial initialization it failed to retrieve the GeoLite2 data from ivre.rocks.

### Expected behavior

Geolite data downloaded and installed.

Command executed: `ivre ipdata --download` from within the container.

### Actual behavior

Download attempt:
```
root@1d8dba340b32:/# ivre ipdata --download
Downloading https://ivre.rocks/data/geolite/GeoLite2-City.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-City.tar.gz: Traceback (most recent call last):
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 941, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/ipdata.py", line 65, in main
    geoiputils.download_all(verbose=not args.quiet)
  File "/usr/local/lib/python3.11/dist-packages/ivre/geoiputils.py", line 227, in download_all
    with opener.open(url) as udesc, open(outfile, "wb") as wdesc:
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

### How to reproduce

It appears as the files are missing from the site: ivre.rocks:

```
GeoLite2-City.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-City.tar.gz
GeoLite2-City-CSV.zip: https://ivre.rocks/data/geolite/GeoLite2-City-CSV.zip
GeoLite2-Country.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-Country.tar.gz
GeoLite2-Country-CSV.zip: https://ivre.rocks/data/geolite/GeoLite2-Country-CSV.zip
GeoLite2-ASN.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-ASN.tar.gz
GeoLite2-ASN-CSV.zip: https://ivre.rocks/data/geolite/GeoLite2-ASN-CSV.zip
GeoLite2-dumps.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-dumps.tar.gz
```

The above all result in 404 - not found at the moment.

```
$ curl -i -k https://ivre.rocks/data/geolite/GeoLite2-dumps.tar.gz
HTTP/2 404
server: nginx
date: Sun, 25 Feb 2024 14:32:17 GMT
content-type: text/html
content-length: 146

<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

This could be temporary, however if there is another method to load this data, I'd appreciate a hint.

cheers
Marco

**Comment by p-l-** [comment]
Based on the error you provide, that is a problem with name resolution from inside the container. You need to check that the containers are allowed to perform DNS requests.

**Comment by hacks2learn** [comment]
After some RTFM'ing I found a workaround:

Create a maxmind.com account (free) and download the geoip databases: https://www.maxmind.com/en/accounts/978559/geoip/downloads 

Put them all into a folder and rename the files to match what IVRE is looking for:

```bash
marco@ubunt:~/ivre/geodata/data/geolite$ ls -l
total 182024
-rwxrwxr-x 1 marco marco  5739405 Feb 25 10:43 GeoLite2-ASN-CSV.zip
-rwxrwxr-x 1 marco marco  4659536 Feb 25 10:43 GeoLite2-ASN.tar.gz
-rwxrwxr-x 1 marco marco 46920477 Feb 25 10:44 GeoLite2-City-CSV.zip
-rwxrwxr-x 1 marco marco 30509317 Feb 25 10:44 GeoLite2-City.tar.gz
-rwxrwxr-x 1 marco marco  3273201 Feb 25 10:44 GeoLite2-Country-CSV.zip
-rwxrwxr-x 1 marco marco  3276873 Feb 25 10:44 GeoLite2-Country.tar.gz
-rw-rw-r-- 1 marco marco 91984895 Feb 26 07:42 GeoLite2-dumps.tar.gz
```

Note: You have to create the *-dumps.tar.gz file

```bash
tar zcvf GeoLite2-dumps.tar.gz GeoLite2-ASN-CSV.zip GeoLite2-ASN.tar.gz GeoLite2-City-CSV.zip GeoLite2-City.tar.gz GeoLite2-Country-CSV.zip GeoLite2-Country.tar.gz
```

Attach to the IVRE client: `sudo docker attach ivreclient`  and update the `/etc/ivre.conf' file to have the following:
**Note: You have to adjust for your own web server IP!**

```bash
DB = "mongodb://ivredb/"
IPDATA_URLS = {
    # None has a special meaning:
    # https://download.maxmind.com/app/geoip_download?edition_id=XXX&suffix=XXX&license_key=XXX
    #
    # You can use this value for the GeoLite2-* files (and set
    # MAXMIND_LICENSE_KEY below) to download files from MaxMind
    # instead of 192.168.75.167:8888 directly. Maxmind license keys are free
    # and can be obtained from <https://www.maxmind.com/>
    "GeoLite2-City.tar.gz": "http://192.168.75.167:8888/data/geolite/GeoLite2-City.tar.gz",
    "GeoLite2-City-CSV.zip": "http://192.168.75.167:8888/data/geolite/GeoLite2-City-CSV.zip",
    "GeoLite2-Country.tar.gz": "http://192.168.75.167:8888/data/geolite/GeoLite2-Country.tar.gz",
    "GeoLite2-Country-CSV.zip": "http://192.168.75.167:8888/data/geolite/GeoLite2-Country-CSV.zip",
    "GeoLite2-ASN.tar.gz": "http://192.168.75.167:8888/data/geolite/GeoLite2-ASN.tar.gz",
    "GeoLite2-ASN-CSV.zip": "http://192.168.75.167:8888/data/geolite/GeoLite2-ASN-CSV.zip",
    # For other files, None has a special meaning "do not
    # download". The following file can be computed based the
    # GeoLite2-* files using `ivre ipdata --import-all`. You should do
    # that if you get your files from Maxmind.
    "GeoLite2-dumps.tar.gz": "http://192.168.75.167:8888/data/geolite/GeoLite2-dumps.tar.gz",
    "iso3166.csv": "https://dev.maxmind.com/csv-files/codes/iso3166.csv",
    # This one is not from maxmind -- see https://thyme.apnic.net/
    "BGP.raw": "https://thyme.apnic.net/current/data-raw-table",
}
```

In the docker container `ivreclient` run:

```bash
root@1d8dba340b32:/# cd /etc
root@1d8dba340b32:/etc# cat > ivre.conf <<END

-- HERE PASTE THE CONF FILE ABOVE AND HIT CARRIAGE RETURN AND TYPE END ---

END
# (you may get an error - ignore it) 
```

You now have basically updated your `ivre.conf` to point to your web server running your local copy of the geoip files.

Start your local python web server in the folder that you have the geoip files in.

```bash
python3 -m http.server 8080
```

Test to make sure you can hit the URL's from the conf file above and the files will download, if all is good, run the command `ivre ipdata --download`  in the docker container `ivreclient`.

```bash
root@1d8dba340b32:/etc# ivre ipdata --download
Downloading http://192.168.75.167:8888/data/geolite/GeoLite2-City.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-City.tar.gz: done.
Downloading http://192.168.75.167:8888/data/geolite/GeoLite2-City-CSV.zip to /usr/local/share/ivre/geoip/GeoLite2-City-CSV.zip: done.
Downloading http://192.168.75.167:8888/data/geolite/GeoLite2-Country.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-Country.tar.gz: done.
Downloading http://192.168.75.167:8888/data/geolite/GeoLite2-Country-CSV.zip to /usr/local/share/ivre/geoip/GeoLite2-Country-CSV.zip: done.
Downloading http://192.168.75.167:8888/data/geolite/GeoLite2-ASN.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-ASN.tar.gz: done.
Downloading http://192.168.75.167:8888/data/geolite/GeoLite2-ASN-CSV.zip to /usr/local/share/ivre/geoip/GeoLite2-ASN-CSV.zip: done.
Downloading http://192.168.75.167:8888/data/geolite/GeoLite2-dumps.tar.gz to /usr/local/share/ivre/geoip/GeoLite2-dumps.tar.gz: done.
Downloading https://dev.maxmind.com/csv-files/codes/iso3166.csv to /usr/local/share/ivre/geoip/iso3166.csv: done.
Downloading https://thyme.apnic.net/current/data-raw-table to /usr/local/share/ivre/geoip/BGP.raw: done.
Unpacking: <function bgp_raw_to_csv at 0x7fb04039c680>(*['BGP.raw', 'BGP.csv'], **{})
<function gunzip at 0x7fb0403d2340>(*['GeoLite2-dumps.tar.gz'], **{})
<function untar_all at 0x7fb0403d23e0>(*['GeoLite2-dumps.tar'], **{'cond': <function <lambda> at 0x7fb0403d28e0>})
done.
```

Your web server should show the files downloaded:

```bash
marco@ubuntu:~/ivre/geodata$ python3 -m http.server 8888
Serving HTTP on 0.0.0.0 port 8888 (http://0.0.0.0:8888/) ...
172.17.0.6 - - [26/Feb/2024 08:46:15] "GET /data/geolite/GeoLite2-City.tar.gz HTTP/1.1" 200 -
172.17.0.6 - - [26/Feb/2024 08:46:15] "GET /data/geolite/GeoLite2-City-CSV.zip HTTP/1.1" 200 -
172.17.0.6 - - [26/Feb/2024 08:46:15] "GET /data/geolite/GeoLite2-Country.tar.gz HTTP/1.1" 200 -
172.17.0.6 - - [26/Feb/2024 08:46:15] "GET /data/geolite/GeoLite2-Country-CSV.zip HTTP/1.1" 200 -
172.17.0.6 - - [26/Feb/2024 08:46:15] "GET /data/geolite/GeoLite2-ASN.tar.gz HTTP/1.1" 200 -
172.17.0.6 - - [26/Feb/2024 08:46:15] "GET /data/geolite/GeoLite2-ASN-CSV.zip HTTP/1.1" 200 -
172.17.0.6 - - [26/Feb/2024 08:46:15] "GET /data/geolite/GeoLite2-dumps.tar.gz HTTP/1.1" 200 -
```

All is good now, you can visit the IVRE site! :)

**Comment by hacks2learn** [comment]
> Based on the error you provide, that is a problem with name resolution from inside the container. You need to check that the containers are allowed to perform DNS requests.

Unfortunately It is a bigger issue than the container, see if you can access any of the ivre.rocks URLS.. 
```
GeoLite2-City.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-City.tar.gz
GeoLite2-City-CSV.zip: https://ivre.rocks/data/geolite/GeoLite2-City-CSV.zip
GeoLite2-Country.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-Country.tar.gz
GeoLite2-Country-CSV.zip: https://ivre.rocks/data/geolite/GeoLite2-Country-CSV.zip
GeoLite2-ASN.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-ASN.tar.gz
GeoLite2-ASN-CSV.zip: https://ivre.rocks/data/geolite/GeoLite2-ASN-CSV.zip
GeoLite2-dumps.tar.gz: https://ivre.rocks/data/geolite/GeoLite2-dumps.tar.gz
```
this is what I get 
![image](https://github.com/ivre/ivre/assets/50385962/7b6948b6-5609-4a58-b97c-e3b32953c410)

**Comment by brandonscholet** [comment]
Why was this closed? The files still seem to not be there?

**Comment by p-l-** [comment]
The command `ivre ipdata --download` works. Doesn't it?

**Comment by afernan31** [comment]
@p-l- it is still not working.. "404 Not found"..

**Comment by afernan31** [comment]
Hello @p-l- , in our case, we cannot create a local web server. This makes this solution invalid and we still have a "404 Not found"..

**Comment by fuad00** [comment]
1. go to `ivre/config.py`
2. find `MAXMIND_LICENSE_KEY = None`
3. Replace with key from Maxmind > Account > Manage license keys
4. recompile/rerun `ivre ipdata --download`
5. profit!
