### ISSUE TITLE
AttributeError: 'MongoDBConnection' object has no attribute 'auth'

### ISSUE THREAD

**Issue by N7MK** [ivre/ivre#1616]
### IVRE Version

```
Version 0.9.20

Python 3.10.12 (main) [GCC 11.4.0]

Linux 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC  x86_64
Dependencies:
    MySQLdb: *missing*
    OpenSSL: 21.0.0
    PIL: 9.0.1
    bottle: 0.12.25
    cryptography: 3.4.8
    dbus: 1.2.18
    krbV: *missing*
    matplotlib: 3.5.1
    psycopg2: 2.9.9 (dt dec pq3 ext lo64)
    pycurl: PycURL/7.44.1 libcurl/7.81.0 GnuTLS/3.7.3 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.17
    pymongo: 4.6.3
    sqlalchemy: 2.0.29
    tinydb: 4.8.0
```

### Summary

Hi there, I'm going to have configured a remote MongoDB with vire.conf  
But a problem arises
```txt
yes | sudo ivre ipinfo --init
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 102, in <module>
    main()
  File "/usr/local/bin/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.10/dist-packages/ivre/tools/ipinfo.py", line 328, in main
    dbase.init()
  File "/usr/local/lib/python3.10/dist-packages/ivre/db/mongo.py", line 298, in init
    self.db[colname].drop()
  File "/usr/local/lib/python3.10/dist-packages/ivre/db/mongo.py", line 220, in db
    return self._db.db
  File "/usr/local/lib/python3.10/dist-packages/ivre/db/mongo.py", line 125, in db
    if not self.auth:
AttributeError: 'MongoDBConnection' object has no attribute 'auth'
```
At this point, I create a .py file to validate the remote DB
```python
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://Username:Pass@test.*.mongodb.net/?retryWrites=true&w=majority&appName=Test"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)
```
OUT
```txt
Pinged your deployment. You successfully connected to MongoDB!
```
It can be confirmed that the remote is available

How can I fix this. Thanks :100:

**Comment by p-l-** [comment]
Can you test with code from current development tree / master branch?

**Comment by p-l-** [comment]
No activity. Please reopen if needed
