### ISSUE TITLE
Python SQLAlchemy attribute and key error while using postgresql

### ISSUE THREAD

**Issue by anoduck** [ivre/ivre#1632]
### IVRE Version

```bash
IVRE - Network recon framework
Copyright 2011 - 2023 Pierre LALET <pierre@droids-corp.org>
Version 0.9.20.dev213

Python 3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0]

Linux box.me.com 6.8.11-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.8.11-1kali2 (2024-05-30) x86_64

Dependencies:
    MySQLdb: 1.4.6
    OpenSSL: 24.2.1
    PIL: 10.3.0
    bottle: 0.12.25
    cryptography: 43.0.0
    dbus: 1.3.2
    krbV: *missing*
    matplotlib: 3.6.3
    psycopg2: 2.9.9 (dt dec pq3 ext lo64)
    pycurl: PycURL/7.45.3 libcurl/8.8.0 OpenSSL/3.2.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.2 libssh2/1.11.0 nghttp2/1.62.1 librtmp/2.3 OpenLDAP/2.5.18
    pymongo: 4.8.0
    sqlalchemy: 1.4.50
    tinydb: 3.15.2
    elasticsearch: 7.17.6
    elasticsearch_dsl: *missing*
```

### Summary

Per Discussions: #1631 

Not only does MongoDB not support my processor architecture, but from experience it places an unnecessarily heavy load on resources. The documentation stated that postgresql could be used as a  "special purpose" databases, it just was unclear if one of those "special purposes" could not be as a replacement for mongodb.

From the error messages recieved, the assumption does not appear to be the case, but rather continuing to make assumptions. It was felt that the best thing to do is report the difficulties for prosperity.

### Expected behavior

As previously mentioned, the assumption was postgresql could be used instead of mongodb. 

### Actual behavior

Logs are included below. More troubleshooting information can be provided if needed, at a later point in time.

### How to reproduce

Running ivre installed from this repository on kali linux rolling release with postgresql version 16. 

### More

```bash
yes | ivre flowcli --init
/usr/local/bin/ivre:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('ivre==0.9.20.dev213', 'ivre')
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 4, in <module>
    __import__('pkg_resources').run_script('ivre==0.9.20.dev213', 'ivre')
  File "/usr/local/lib/python3.11/dist-packages/pkg_resources/__init__.py", line 691, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.11/dist-packages/pkg_resources/__init__.py", line 1530, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.11/dist-packages/ivre-0.9.20.dev213-py3.11.egg/EGG-INFO/scripts/ivre", line 102, in <module>
    main()
  File "/usr/local/lib/python3.11/dist-packages/ivre-0.9.20.dev213-py3.11.egg/EGG-INFO/scripts/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/flowcli.py", line 268, in main
    db.flow.init()
  File "/usr/local/lib/python3.11/dist-packages/ivre/db/sql/__init__.py", line 304, in init
    self.create()
  File "/usr/local/lib/python3.11/dist-packages/ivre/db/sql/__init__.py", line 300, in create
    table.__table__.create(bind=self.db, checkfirst=True)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 962, in create
    bind._run_ddl_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 3238, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)er smartd[1096]: Device: /dev/sda [SAT], SMART Usage Attribute: 190 Airflow_Temperature_Cel changed from 71 to 69
2024-08-14T18:38:41.854601-04:00 demeter smartd[1096]: Device: /dev/sda [SAT], SMART Usage Attribute: 194 Temperature_Celsius changed from 29 to 31

  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 899, in visit_table
    self.connection.execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1474, in _execute_ddl
    compiled = ddl.compile(
               ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 503, in compile
    return self._compiler(dialect, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/ddl.py", line 32, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 464, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 499, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 4599, in visit_create_table
    const = self.create_table_constraints(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 4648, in create_table_constraints
    return ", \n\t".join(
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 4648, in <genexpr>
    return ", \n\t".join(
                        ^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 4651, in <genexpr>
    self.process(constraint)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 499, in process
    return obj._compiler_dispatch(self, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/visitors.py", line 82, in _compiler_dispatch
    return meth(self, **kw)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/dialects/postgresql/base.py", line 2783, in visit_foreign_key_constraint
    text = super(PGDDLCompiler, self).visit_foreign_key_constraint(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/compiler.py", line 4932, in visit_foreign_key_constraint
    remote_table = list(constraint.elements)[0].column.table
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 1113, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 2532, in column
    return self._resolve_column()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/schema.py", line 2543, in _resolve_column
    raise exc.NoReferencedTableError(
sqlalchemy.exc.NoReferencedTableError: Foreign key associated with column 'flow.src' could not find table 'host' with which to generate a foreign key to target column 'id'

ivre-apache # yes | sudo ivre runscansagentdb --init
/usr/local/bin/ivre:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('ivre==0.9.20.dev213', 'ivre')
ERROR:ivre:Cannot get database for DBAgent from postgresql://ivre@localhost/ivredb
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/ivre/db/__init__.py", line 281, in from_url
    modulename, classname = cls.backends[db_type]
                            ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'postgresql'
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 4, in <module>
    __import__('pkg_resources').run_script('ivre==0.9.20.dev213', 'ivre')
  File "/usr/local/lib/python3.11/dist-packages/pkg_resources/__init__.py", line 691, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.11/dist-packages/pkg_resources/__init__.py", line 1530, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.11/dist-packages/ivre-0.9.20.dev213-py3.11.egg/EGG-INFO/scripts/ivre", line 102, in <module>
    main()
  File "/usr/local/lib/python3.11/dist-packages/ivre-0.9.20.dev213-py3.11.egg/EGG-INFO/scripts/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/runscansagentdb.py", line 175, in main
    ivre.db.db.agent.init()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'init'

# -------------------------------------------------------------------

/home/ivre-apache ï 1 â¯ yes | ivre runscansagentdb --init

/usr/local/bin/ivre:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('ivre==0.9.20.dev213', 'ivre')
ERROR:ivre:Cannot get database for DBAgent from postgresql://ivre@localhost/ivredb
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/ivre/db/__init__.py", line 281, in from_url
    modulename, classname = cls.backends[db_type]
                            ~~~~~~~~~~~~^^^^^^^^^
KeyError: 'postgresql'
Traceback (most recent call last):
  File "/usr/local/bin/ivre", line 4, in <module>
    __import__('pkg_resources').run_script('ivre==0.9.20.dev213', 'ivre')
  File "/usr/local/lib/python3.11/dist-packages/pkg_resources/__init__.py", line 691, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.11/dist-packages/pkg_resources/__init__.py", line 1530, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.11/dist-packages/ivre-0.9.20.dev213-py3.11.egg/EGG-INFO/scripts/ivre", line 102, in <module>
    main()
  File "/usr/local/lib/python3.11/dist-packages/ivre-0.9.20.dev213-py3.11.egg/EGG-INFO/scripts/ivre", line 70, in main
    tools.get_command(next(iter(possible_commands)))()
  File "/usr/local/lib/python3.11/dist-packages/ivre/tools/runscansagentdb.py", line 175, in main
    ivre.db.db.agent.init()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'init'

```

Highly probably the message is unrelated, but including it anyway from the postgresql log file.

```bash
2024-08-14 17:56:16.078 EDT [3784561] FATAL:  could not load private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied
2024-08-14 17:56:16.079 EDT [3784561] LOG:  database system is shut down
pg_ctl: could not start server
Examine the log output.
```

**Comment by p-l-** [comment]
Hi there,

Thanks for your interest in IVRE and for this report. Unfortunately the PostgreSQL backend is more of an experiment and I don't have time to test & maintain it. I'll leave this issue open in case someone can help you.

May I ask you why you have chosen PostgreSQL? If you're interested in using IVRE, I'd really suggest that you use MongoDB (or TinyDB if you only plan to have a small database). If you're interested in developing IVRE's PostgreSQL backend, please let me know!

**Comment by anoduck** [comment]
> May I ask you why you have chosen PostgreSQL? If you're interested in using IVRE, I'd really suggest that you use MongoDB (or TinyDB if you only plan to have a small database). If you're interested in developing IVRE's PostgreSQL backend, please let me know!

MongoDB does not support my four core processor, which is of an older make. Even with the systems it does support, I have found MongoDB to be load heavy, comparatively. This may have changed since I last used it, even postgresql isn't as easy to configure as it used to be.

**Comment by p-l-** [comment]
Have you tried an older MongoDB version? IVRE supports quite old versions if that may help.

**Comment by anoduck** [comment]
> Have you tried an older MongoDB version? IVRE supports quite old versions if that may help.

I am most definitely going to try that out, because I have wanted to use IVRE for some time now.

**Comment by anoduck** [comment]
@p-l- It is really down to the matter of finding a source to acquire the appropriate MongoDB revision. 

It was in the >= 4.0 release, where mongodb began to require CPUs that support AVX. The newest revision that does not require AVX is for mongodb-enterprise 3.7. It resolves to the debian jessie repository and when tested, apt ignored the repository rather than scanning it for available packages. 

Having said this, as a matter of pure chance, [a repository](https://github.com/GermanAizek/mongodb-without-avx) was discovered that claimed to provide the necessary patches to build mongodb from source without the requirement of AVX support. If this option is valid and successful, it would be the best means to resolve encountered difficulties. 

So, after having laid out the available paths towards a resolution, this issue will be closed out.

**Comment by p-l-** [comment]
Nice!

**Comment by anoduck** [comment]
Fingers crossed. The first run of the patch files we not conducive to a successful build, but this might be a result of not following strict versioning.
